name: Tag

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
# test 1212
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello world!"
