name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
#          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: log
        run: |
          git log -20 --pretty=format:"%h - %an, %ar : %s"
      - name: Generate Changelog
        run: |
          info=$(git log -1 --pretty=format:"%b" $(git log -2 --pretty=format:"%h" | tail -n 1)) 
          echo "$info" > ${{ github.workspace }}-CHANGELOG.txt

