name: release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Changelog
        run: |
          info=$(git log -1 --pretty=format:"%b" $(git log -2 --pretty=format:"%h" | tail -n 1)) 
          echo "$info" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
