name: Tag

on:
  push:
#    branches:
#      - master
    tags:
      - "v*.*.*"
# test 1212
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
